// Generated by psc version 0.6.9.5
var PS = PS || {};
PS.Prelude = (function () {
    "use strict";
    
    function cons(e) {
      return function(l) {
        return [e].concat(l);
      };
    }
    ;
    
    function numAdd(n1) {
      return function(n2) {
        return n1 + n2;
      };
    }
    ;
    
    function numSub(n1) {
      return function(n2) {
        return n1 - n2;
      };
    }
    ;
    
    function numMul(n1) {
      return function(n2) {
        return n1 * n2;
      };
    }
    ;
    
    function refEq(r1) {
      return function(r2) {
        return r1 === r2;
      };
    }
    ;
    
    function refIneq(r1) {
      return function(r2) {
        return r1 !== r2;
      };
    }
    ;
    
    function unsafeCompareImpl(lt) {
      return function(eq) {
        return function(gt) {
          return function(x) {
            return function(y) {
              return x < y ? lt : x > y ? gt : eq;
            };
          };
        };
      };
    }
    ;
    
    function boolAnd(b1) {
      return function(b2) {
        return b1 && b2;
      };
    }
    ;
    
    function boolOr(b1) {
      return function(b2) {
        return b1 || b2;
      };
    }
    ;
    
    function boolNot(b) {
      return !b;
    }
    ;
    
    function concatString(s1) {
      return function(s2) {
        return s1 + s2;
      };
    }
    ;
    var LT = (function () {
        function LT() {

        };
        LT.value = new LT();
        return LT;
    })();
    var GT = (function () {
        function GT() {

        };
        GT.value = new GT();
        return GT;
    })();
    var EQ = (function () {
        function EQ() {

        };
        EQ.value = new EQ();
        return EQ;
    })();
    var Semigroupoid = function ($less$less$less) {
        this["<<<"] = $less$less$less;
    };
    var Functor = function ($less$dollar$greater) {
        this["<$>"] = $less$dollar$greater;
    };
    var Apply = function ($less$times$greater, __superclass_Prelude$dotFunctor_0) {
        this["<*>"] = $less$times$greater;
        this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
    };
    var Applicative = function (__superclass_Prelude$dotApply_0, pure) {
        this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
        this.pure = pure;
    };
    var Bind = function ($greater$greater$eq, __superclass_Prelude$dotApply_0) {
        this[">>="] = $greater$greater$eq;
        this["__superclass_Prelude.Apply_0"] = __superclass_Prelude$dotApply_0;
    };
    var Monad = function (__superclass_Prelude$dotApplicative_0, __superclass_Prelude$dotBind_1) {
        this["__superclass_Prelude.Applicative_0"] = __superclass_Prelude$dotApplicative_0;
        this["__superclass_Prelude.Bind_1"] = __superclass_Prelude$dotBind_1;
    };
    var Semiring = function ($times, $plus, one, zero) {
        this["*"] = $times;
        this["+"] = $plus;
        this.one = one;
        this.zero = zero;
    };
    var Ring = function ($minus, __superclass_Prelude$dotSemiring_0) {
        this["-"] = $minus;
        this["__superclass_Prelude.Semiring_0"] = __superclass_Prelude$dotSemiring_0;
    };
    var Eq = function ($div$eq, $eq$eq) {
        this["/="] = $div$eq;
        this["=="] = $eq$eq;
    };
    var Ord = function (__superclass_Prelude$dotEq_0, compare) {
        this["__superclass_Prelude.Eq_0"] = __superclass_Prelude$dotEq_0;
        this.compare = compare;
    };
    var BoolLike = function ($amp$amp, not, $bar$bar) {
        this["&&"] = $amp$amp;
        this.not = not;
        this["||"] = $bar$bar;
    };
    var Semigroup = function ($less$greater) {
        this["<>"] = $less$greater;
    };
    var $greater$greater$eq = function (dict) {
        return dict[">>="];
    };
    var $eq$eq = function (dict) {
        return dict["=="];
    };
    var $less$greater = function (dict) {
        return dict["<>"];
    };
    var $less$less$less = function (dict) {
        return dict["<<<"];
    };
    var $less$times$greater = function (dict) {
        return dict["<*>"];
    };
    var $less$dollar$greater = function (dict) {
        return dict["<$>"];
    };
    var $colon = cons;
    var $minus = function (dict) {
        return dict["-"];
    };
    var $plus$plus = function (__dict_Semigroup_2) {
        return $less$greater(__dict_Semigroup_2);
    };
    var $plus = function (dict) {
        return dict["+"];
    };
    var $times = function (dict) {
        return dict["*"];
    };
    var $amp$amp = function (dict) {
        return dict["&&"];
    };
    var $dollar = function (f) {
        return function (x) {
            return f(x);
        };
    };
    var zero = function (dict) {
        return dict.zero;
    };
    var unsafeCompare = unsafeCompareImpl(LT.value)(EQ.value)(GT.value);
    var semiringNumber = new Semiring(numMul, numAdd, 1, 0);
    var semigroupoidArr = new Semigroupoid(function (f) {
        return function (g) {
            return function (x) {
                return f(g(x));
            };
        };
    });
    var semigroupString = new Semigroup(concatString);
    var ringNumber = new Ring(numSub, function () {
        return semiringNumber;
    });
    var pure = function (dict) {
        return dict.pure;
    };
    var $$return = function (__dict_Monad_5) {
        return pure(__dict_Monad_5["__superclass_Prelude.Applicative_0"]());
    };
    var not = function (dict) {
        return dict.not;
    };
    var negate = function (__dict_Ring_6) {
        return function (a) {
            return $minus(__dict_Ring_6)(zero(__dict_Ring_6["__superclass_Prelude.Semiring_0"]()))(a);
        };
    };
    var liftA1 = function (__dict_Applicative_8) {
        return function (f) {
            return function (a) {
                return $less$times$greater(__dict_Applicative_8["__superclass_Prelude.Apply_0"]())(pure(__dict_Applicative_8)(f))(a);
            };
        };
    };
    var flip = function (f) {
        return function (b) {
            return function (a) {
                return f(a)(b);
            };
        };
    };
    var eqNumber = new Eq(refIneq, refEq);
    var ordNumber = new Ord(function () {
        return eqNumber;
    }, unsafeCompare);
    var compare = function (dict) {
        return dict.compare;
    };
    var $less = function (__dict_Ord_12) {
        return function (a1) {
            return function (a2) {
                var _260 = compare(__dict_Ord_12)(a1)(a2);
                if (_260 instanceof LT) {
                    return true;
                };
                return false;
            };
        };
    };
    var $less$eq = function (__dict_Ord_13) {
        return function (a1) {
            return function (a2) {
                var _261 = compare(__dict_Ord_13)(a1)(a2);
                if (_261 instanceof GT) {
                    return false;
                };
                return true;
            };
        };
    };
    var $greater = function (__dict_Ord_14) {
        return function (a1) {
            return function (a2) {
                var _262 = compare(__dict_Ord_14)(a1)(a2);
                if (_262 instanceof GT) {
                    return true;
                };
                return false;
            };
        };
    };
    var boolLikeBoolean = new BoolLike(boolAnd, boolNot, boolOr);
    var ap = function (__dict_Monad_16) {
        return function (f) {
            return function (a) {
                return $greater$greater$eq(__dict_Monad_16["__superclass_Prelude.Bind_1"]())(f)(function (_2) {
                    return $greater$greater$eq(__dict_Monad_16["__superclass_Prelude.Bind_1"]())(a)(function (_1) {
                        return $$return(__dict_Monad_16)(_2(_1));
                    });
                });
            };
        };
    };
    return {
        LT: LT, 
        GT: GT, 
        EQ: EQ, 
        Semigroup: Semigroup, 
        BoolLike: BoolLike, 
        Ord: Ord, 
        Eq: Eq, 
        Ring: Ring, 
        Semiring: Semiring, 
        Monad: Monad, 
        Bind: Bind, 
        Applicative: Applicative, 
        Apply: Apply, 
        Functor: Functor, 
        Semigroupoid: Semigroupoid, 
        "++": $plus$plus, 
        "<>": $less$greater, 
        not: not, 
        "&&": $amp$amp, 
        "<=": $less$eq, 
        ">": $greater, 
        "<": $less, 
        compare: compare, 
        "==": $eq$eq, 
        negate: negate, 
        "-": $minus, 
        "*": $times, 
        zero: zero, 
        "+": $plus, 
        ap: ap, 
        "return": $$return, 
        ">>=": $greater$greater$eq, 
        liftA1: liftA1, 
        pure: pure, 
        "<*>": $less$times$greater, 
        "<$>": $less$dollar$greater, 
        cons: cons, 
        ":": $colon, 
        "$": $dollar, 
        "<<<": $less$less$less, 
        flip: flip, 
        semigroupoidArr: semigroupoidArr, 
        semiringNumber: semiringNumber, 
        ringNumber: ringNumber, 
        eqNumber: eqNumber, 
        ordNumber: ordNumber, 
        boolLikeBoolean: boolLikeBoolean, 
        semigroupString: semigroupString
    };
})();
var PS = PS || {};
PS.$$Math = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var abs = Math.abs;;
    function max(n1){  return function(n2) {    return Math.max(n1, n2);  }};
    function min(n1){  return function(n2) {    return Math.min(n1, n2);  }};
    return {
        min: min, 
        max: max, 
        abs: abs
    };
})();
var PS = PS || {};
PS.Mario = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var $$Math = PS.$$Math;
    var Left = (function () {
        function Left() {

        };
        Left.value = new Left();
        return Left;
    })();
    var Right = (function () {
        function Right() {

        };
        Right.value = new Right();
        return Right;
    })();
    var Jumping = (function () {
        function Jumping() {

        };
        Jumping.value = new Jumping();
        return Jumping;
    })();
    var Walking = (function () {
        function Walking() {

        };
        Walking.value = new Walking();
        return Walking;
    })();
    var Standing = (function () {
        function Standing() {

        };
        Standing.value = new Standing();
        return Standing;
    })();
    var velocity = function (s) {
        var _265 = {};
        for (var _266 in s) {
            if (s.hasOwnProperty(_266)) {
                _265[_266] = s[_266];
            };
        };
        _265.x = s.x + s.dx;
        _265.y = s.y + s.dy;
        return _265;
    };
    var minJumpHeight = 3;
    var maxMoveSpeed = 2.5;
    var marioSpriteUrl = function (activity) {
        return function (dir) {
            var dirPath = function (_39) {
                if (_39 instanceof Left) {
                    return "left";
                };
                if (_39 instanceof Right) {
                    return "right";
                };
                throw new Error("Failed pattern match");
            };
            var activityPath = function (_38) {
                if (_38 instanceof Jumping) {
                    return "jump";
                };
                if (_38 instanceof Walking) {
                    return "walk";
                };
                if (_38 instanceof Standing) {
                    return "stand";
                };
                throw new Error("Failed pattern match");
            };
            return "resources/mario/" + (activityPath(activity) + ("/" + (dirPath(dir) + ".gif")));
        };
    };
    var jumpCoefficient = 0.4;
    var jumpSpeed = function (dx) {
        return minJumpHeight + jumpCoefficient * $$Math.abs(dx);
    };
    var isAirborne = function (s) {
        return s.y > 0;
    };
    var groundFriction = 0.1;
    var groundAccel = 6.0e-2;
    var gravity = 0.2;
    var jump = function (_35) {
        return function (s) {
            if (_35 && !isAirborne(s)) {
                var _271 = {};
                for (var _272 in s) {
                    if (s.hasOwnProperty(_272)) {
                        _271[_272] = s[_272];
                    };
                };
                _271.dy = jumpSpeed(s.dx);
                return _271;
            };
            if (!_35 && (isAirborne(s) && s.dy > 0)) {
                var _273 = {};
                for (var _274 in s) {
                    if (s.hasOwnProperty(_274)) {
                        _273[_274] = s[_274];
                    };
                };
                _273.dy = s.dy - gravity;
                return _273;
            };
            return s;
        };
    };
    var initialState = jump(true)({
        x: -40, 
        y: 0, 
        dx: maxMoveSpeed, 
        dy: 0, 
        dir: Right.value
    });
    var currentActivity = function (s) {
        if (isAirborne(s)) {
            return Jumping.value;
        };
        if (s.dx === 0) {
            return Standing.value;
        };
        return Walking.value;
    };
    var applyGravity = function (s) {
        if (s.y <= -s.dy) {
            var _277 = {};
            for (var _278 in s) {
                if (s.hasOwnProperty(_278)) {
                    _277[_278] = s[_278];
                };
            };
            _277.y = 0;
            _277.dy = 0;
            return _277;
        };
        var _279 = {};
        for (var _280 in s) {
            if (s.hasOwnProperty(_280)) {
                _279[_280] = s[_280];
            };
        };
        _279.y = s.y + s.dy;
        _279.dy = s.dy - gravity;
        return _279;
    };
    var airFriction = 2.0e-2;
    var friction = function (s) {
        var _281 = isAirborne(s);
        if (_281) {
            return airFriction;
        };
        if (!_281) {
            return groundFriction;
        };
        throw new Error("Failed pattern match");
    };
    var applyFriction = function (s) {
        if (s.dx === 0) {
            return s;
        };
        if ($$Math.abs(s.dx) <= friction(s)) {
            var _283 = {};
            for (var _284 in s) {
                if (s.hasOwnProperty(_284)) {
                    _283[_284] = s[_284];
                };
            };
            _283.dx = 0;
            return _283;
        };
        if (s.dx > 0) {
            var _285 = {};
            for (var _286 in s) {
                if (s.hasOwnProperty(_286)) {
                    _285[_286] = s[_286];
                };
            };
            _285.dx = s.dx - friction(s);
            return _285;
        };
        if (s.dx < 0) {
            var _287 = {};
            for (var _288 in s) {
                if (s.hasOwnProperty(_288)) {
                    _287[_288] = s[_288];
                };
            };
            _287.dx = s.dx + friction(s);
            return _287;
        };
        throw new Error("Failed pattern match");
    };
    var airAccel = 4.0e-2;
    var accel = function (s) {
        var _289 = isAirborne(s);
        if (_289) {
            return airAccel;
        };
        if (!_289) {
            return groundAccel;
        };
        throw new Error("Failed pattern match");
    };
    var walk = function (_36) {
        return function (_37) {
            return function (s) {
                if (_36 && !_37) {
                    var s$prime = (function () {
                        var _293 = s.dx > 0;
                        if (_293) {
                            return applyFriction(s);
                        };
                        if (!_293) {
                            return s;
                        };
                        throw new Error("Failed pattern match");
                    })();
                    var _294 = {};
                    for (var _295 in s$prime) {
                        if (s$prime.hasOwnProperty(_295)) {
                            _294[_295] = s$prime[_295];
                        };
                    };
                    _294.dx = $$Math.max(-maxMoveSpeed)(s$prime.dx - accel(s$prime));
                    _294.dir = Left.value;
                    return _294;
                };
                if (!_36 && _37) {
                    var s$prime = (function () {
                        var _296 = s.dx < 0;
                        if (_296) {
                            return applyFriction(s);
                        };
                        if (!_296) {
                            return s;
                        };
                        throw new Error("Failed pattern match");
                    })();
                    var _297 = {};
                    for (var _298 in s$prime) {
                        if (s$prime.hasOwnProperty(_298)) {
                            _297[_298] = s$prime[_298];
                        };
                    };
                    _297.dx = $$Math.min(maxMoveSpeed)(s$prime.dx + accel(s$prime));
                    _297.dir = Right.value;
                    return _297;
                };
                return applyFriction(s);
            };
        };
    };
    var marioLogic = function (inputs) {
        return Prelude["<<<"](Prelude.semigroupoidArr)(velocity)(Prelude["<<<"](Prelude.semigroupoidArr)(applyGravity)(Prelude["<<<"](Prelude.semigroupoidArr)(walk(inputs.left)(inputs.right))(jump(inputs.jump))));
    };
    return {
        Jumping: Jumping, 
        Walking: Walking, 
        Standing: Standing, 
        Left: Left, 
        Right: Right, 
        marioLogic: marioLogic, 
        applyFriction: applyFriction, 
        walk: walk, 
        jump: jump, 
        jumpSpeed: jumpSpeed, 
        applyGravity: applyGravity, 
        velocity: velocity, 
        friction: friction, 
        accel: accel, 
        currentActivity: currentActivity, 
        isAirborne: isAirborne, 
        marioSpriteUrl: marioSpriteUrl, 
        airFriction: airFriction, 
        groundFriction: groundFriction, 
        airAccel: airAccel, 
        groundAccel: groundAccel, 
        maxMoveSpeed: maxMoveSpeed, 
        minJumpHeight: minJumpHeight, 
        jumpCoefficient: jumpCoefficient, 
        gravity: gravity, 
        initialState: initialState
    };
})();
var PS = PS || {};
PS.Data_Function = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    
    function runFn2(fn) {
      return function(a) {
        return function(b) {
          return fn(a, b);
        };
      };
    }
    ;
    
    function runFn3(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return fn(a, b, c);
          };
        };
      };
    }
    ;
    
    function runFn4(fn) {
      return function(a) {
        return function(b) {
          return function(c) {
            return function(d) {
              return fn(a, b, c, d);
            };
          };
        };
      };
    }
    ;
    return {
        runFn4: runFn4, 
        runFn3: runFn3, 
        runFn2: runFn2
    };
})();
var PS = PS || {};
PS.Control_Monad_Eff = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    
    function returnE(a) {
      return function() {
        return a;
      };
    }
    ;
    
    function bindE(a) {
      return function(f) {
        return function() {
          return f(a())();
        };
      };
    }
    ;
    var monadEff = new Prelude.Monad(function () {
        return applicativeEff;
    }, function () {
        return bindEff;
    });
    var bindEff = new Prelude.Bind(bindE, function () {
        return applyEff;
    });
    var applyEff = new Prelude.Apply(Prelude.ap(monadEff), function () {
        return functorEff;
    });
    var applicativeEff = new Prelude.Applicative(function () {
        return applyEff;
    }, returnE);
    var functorEff = new Prelude.Functor(Prelude.liftA1(applicativeEff));
    return {
        functorEff: functorEff, 
        applyEff: applyEff, 
        applicativeEff: applicativeEff, 
        bindEff: bindEff, 
        monadEff: monadEff
    };
})();
var PS = PS || {};
PS.Signal = (function () {
    "use strict";
    var Data_Function = PS.Data_Function;
    var Prelude = PS.Prelude;
    var Control_Monad_Eff = PS.Control_Monad_Eff;
    
  function constant(initial) {
    var subs = [];
    var val = initial;
    var sig = {
      subscribe: function(sub) {
        subs.push(sub);
        sub(val);
      },
      get: function() { return val; },
      set: function(newval) {
        val = newval;
        subs.forEach(function(sub) { sub(newval); });
      }
    };
    return sig;
  };
    
  function mapP(constant, fun, sig) {
    var out = constant(fun(sig.get()));
    sig.subscribe(function(val) { out.set(fun(val)); });
    return out;
  };
    
  function applySigP(constant, fun, sig) {
    var out = constant(fun.get()(sig.get()));
    var produce = function() { out.set(fun.get()(sig.get())); };
    fun.subscribe(produce);
    sig.subscribe(produce);
    return out;
  };
    
  function mergeP(constant, sig1, sig2) {
    var out = constant(sig1.get());
    sig1.subscribe(out.set);
    sig2.subscribe(out.set);
    return out;
  };
    
  function foldpP(constant, fun, seed, sig) {
    var acc = seed;
    var out = constant(acc);
    sig.subscribe(function(val) {
      acc = fun(val)(acc);
      out.set(acc);
    });
    return out;
  };
    
  function sampleOnP(constant, sig1, sig2) {
    var out = constant(sig2.get());
    sig1.subscribe(function() {
      out.set(sig2.get());
    });
    return out;
  };
    
  function runSignal(sig) {
    return function() {
      sig.subscribe(function(val) {
        val();
      });
      return {};
    };
  };
    var $tilde$greater = function (__dict_Functor_18) {
        return Prelude.flip(Prelude["<$>"](__dict_Functor_18));
    };
    var sampleOn = Data_Function.runFn3(sampleOnP)(constant);
    var merge = Data_Function.runFn3(mergeP)(constant);
    var map = Data_Function.runFn3(mapP)(constant);
    var functorSignal = new Prelude.Functor(map);
    var foldp = Data_Function.runFn4(foldpP)(constant);
    var applySig = Data_Function.runFn3(applySigP)(constant);
    var applySignal = new Prelude.Apply(applySig, function () {
        return functorSignal;
    });
    return {
        "~>": $tilde$greater, 
        runSignal: runSignal, 
        sampleOn: sampleOn, 
        foldp: foldp, 
        merge: merge, 
        applySig: applySig, 
        map: map, 
        constant: constant, 
        functorSignal: functorSignal, 
        applySignal: applySignal
    };
})();
var PS = PS || {};
PS.Signal_Time = (function () {
    "use strict";
    var Data_Function = PS.Data_Function;
    var Signal = PS.Signal;
    var Prelude = PS.Prelude;
    var Control_Monad_Eff = PS.Control_Monad_Eff;
    var Control_Timer = PS.Control_Timer;
    
  function now() {
    var perf = typeof performance !== 'undefined' ? performance : null,
        proc = typeof process !== 'undefined' ? process : null;
    return (
      perf && (perf.now || perf.webkitNow || perf.msNow || perf.oNow || perf.mozNow) ||
      (proc && proc.hrtime && function() {
        var t = proc.hrtime();
        return (t[0] * 1e9 + t[1]) / 1e6;
      }) ||
      Date.now
    ).call(perf);
  };
    return {
        now: now
    };
})();
var PS = PS || {};
PS.Signal_DOM = (function () {
    "use strict";
    var Data_Function = PS.Data_Function;
    var Signal = PS.Signal;
    var Prelude = PS.Prelude;
    var Signal_Time = PS.Signal_Time;
    var Control_Monad_Eff = PS.Control_Monad_Eff;
    var Control_Timer = PS.Control_Timer;
    var DOM = PS.DOM;
    
  function keyPressedP(constant, keyCode) {
    return function() {
      var out = constant(false);
      window.addEventListener("keydown", function(e) {
        if (e.keyCode === keyCode) out.set(true);
      });
      window.addEventListener("keyup", function(e) {
        if (e.keyCode === keyCode) out.set(false);
      });
      return out;
    };
  };
    
  function animationFrameP(constant, now) {
    return function() {
      var requestAnimFrame, cancelAnimFrame;
      if (window.requestAnimationFrame) {
        requestAnimFrame = window.requestAnimationFrame;
        cancelAnimFrame = window.cancelAnimationFrame;
      } else if (window.mozRequestAnimationFrame) {
        requestAnimFrame = window.mozRequestAnimationFrame;
        cancelAnimFrame = window.mozCancelAnimationFrame;
      } else if (window.webkitRequestAnimationFrame) {
        requestAnimFrame = window.webkitRequestAnimationFrame;
        cancelAnimFrame = window.webkitCancelAnimationFrame;
      } else if (window.msRequestAnimationFrame) {
        requestAnimFrame = window.msRequestAnimationFrame;
        cancelAnimFrame = window.msCancelAnimationFrame;
      } else if (window.oRequestAnimationFrame) {
        requestAnimFrame = window.oRequestAnimationFrame;
        cancelAnimFrame = window.oCancelAnimationFrame;
      } else {
        requestAnimFrame = function(cb) {setTimeout(function() {cb(now())}, 1000/60)};
        cancelAnimFrame = window.clearTimeout;
      }
      var out = constant(now());
      requestAnimFrame(function tick(t) {
        out.set(t); requestAnimFrame(tick);
      });
      return out;
    };
  };
    var keyPressed = Data_Function.runFn2(keyPressedP)(Signal.constant);
    var animationFrame = animationFrameP(Signal.constant, Signal_Time.now);
    return {
        keyPressed: keyPressed, 
        animationFrame: animationFrame
    };
})();
var PS = PS || {};
PS.Data_Array = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Data_Maybe = PS.Data_Maybe;
    var Control_Alt = PS.Control_Alt;
    var Control_Plus = PS.Control_Plus;
    var Control_Alternative = PS.Control_Alternative;
    var Control_MonadPlus = PS.Control_MonadPlus;
    var Prelude_Unsafe = PS.Prelude_Unsafe;
    function map (f) {  return function (arr) {    var l = arr.length;    var result = new Array(l);    for (var i = 0; i < l; i++) {      result[i] = f(arr[i]);    }    return result;  };};
    var functorArray = new Prelude.Functor(map);
    return {
        map: map, 
        functorArray: functorArray
    };
})();
var PS = PS || {};
PS.Data_Monoid = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Data_Array = PS.Data_Array;
    var Data_Maybe = PS.Data_Maybe;
    var mempty = function (dict) {
        return dict.mempty;
    };
    return {
        mempty: mempty
    };
})();
var PS = PS || {};
PS.Data_Foldable = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Data_Monoid = PS.Data_Monoid;
    var Control_Apply = PS.Control_Apply;
    var Data_Monoid_First = PS.Data_Monoid_First;
    var Data_Either = PS.Data_Either;
    var Data_Maybe = PS.Data_Maybe;
    var Data_Monoid_Additive = PS.Data_Monoid_Additive;
    var Data_Monoid_Dual = PS.Data_Monoid_Dual;
    var Data_Monoid_Last = PS.Data_Monoid_Last;
    var Data_Monoid_Multiplicative = PS.Data_Monoid_Multiplicative;
    var Data_Tuple = PS.Data_Tuple;
    
  function foldrArray(f) {
    return function(z) {
      return function(xs) {
        var acc = z;
        for (var i = xs.length - 1; i >= 0; --i) {
          acc = f(xs[i])(acc);
        }
        return acc;
      };
    };
  }
  ;
    
  function foldlArray(f) {
    return function(z) {
      return function(xs) {
        var acc = z;
        for (var i = 0, len = xs.length; i < len; ++i) {
          acc = f(acc)(xs[i]);
        }
        return acc;
      };
    };
  }
  ;
    var Foldable = function (foldMap, foldl, foldr) {
        this.foldMap = foldMap;
        this.foldl = foldl;
        this.foldr = foldr;
    };
    var foldr = function (dict) {
        return dict.foldr;
    };
    var foldl = function (dict) {
        return dict.foldl;
    };
    var foldableArray = new Foldable(function (__dict_Monoid_134) {
        return function (f) {
            return function (xs) {
                return foldr(foldableArray)(function (x) {
                    return function (acc) {
                        return Prelude["<>"](__dict_Monoid_134["__superclass_Prelude.Semigroup_0"]())(f(x))(acc);
                    };
                })(Data_Monoid.mempty(__dict_Monoid_134))(xs);
            };
        };
    }, function (f) {
        return function (z) {
            return function (xs) {
                return foldlArray(f)(z)(xs);
            };
        };
    }, function (f) {
        return function (z) {
            return function (xs) {
                return foldrArray(f)(z)(xs);
            };
        };
    });
    return {
        Foldable: Foldable, 
        foldlArray: foldlArray, 
        foldrArray: foldrArray, 
        foldl: foldl, 
        foldr: foldr, 
        foldableArray: foldableArray
    };
})();
var PS = PS || {};
PS.Data_Traversable = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Data_Array = PS.Data_Array;
    var Data_Tuple = PS.Data_Tuple;
    var Data_Either = PS.Data_Either;
    var Data_Foldable = PS.Data_Foldable;
    var Data_Maybe = PS.Data_Maybe;
    var Data_Monoid_Additive = PS.Data_Monoid_Additive;
    var Data_Monoid_Dual = PS.Data_Monoid_Dual;
    var Data_Monoid_First = PS.Data_Monoid_First;
    var Data_Monoid_Last = PS.Data_Monoid_Last;
    var Data_Monoid_Multiplicative = PS.Data_Monoid_Multiplicative;
    var Traversable = function (__superclass_Data$dotFoldable$dotFoldable_1, __superclass_Prelude$dotFunctor_0, sequence, traverse) {
        this["__superclass_Data.Foldable.Foldable_1"] = __superclass_Data$dotFoldable$dotFoldable_1;
        this["__superclass_Prelude.Functor_0"] = __superclass_Prelude$dotFunctor_0;
        this.sequence = sequence;
        this.traverse = traverse;
    };
    var traverse = function (dict) {
        return dict.traverse;
    };
    var sequence = function (dict) {
        return dict.sequence;
    };
    var traversableArray = new Traversable(function () {
        return Data_Foldable.foldableArray;
    }, function () {
        return Data_Array.functorArray;
    }, function (__dict_Applicative_163) {
        return function (_243) {
            if (_243.length === 0) {
                return Prelude.pure(__dict_Applicative_163)([  ]);
            };
            if (_243.length >= 1) {
                var _301 = _243.slice(1);
                return Prelude["<*>"](__dict_Applicative_163["__superclass_Prelude.Apply_0"]())(Prelude["<$>"]((__dict_Applicative_163["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(Prelude[":"])(_243[0]))(sequence(traversableArray)(__dict_Applicative_163)(_301));
            };
            throw new Error("Failed pattern match");
        };
    }, function (__dict_Applicative_162) {
        return function (f) {
            return function (_242) {
                if (_242.length === 0) {
                    return Prelude.pure(__dict_Applicative_162)([  ]);
                };
                if (_242.length >= 1) {
                    var _305 = _242.slice(1);
                    return Prelude["<*>"](__dict_Applicative_162["__superclass_Prelude.Apply_0"]())(Prelude["<$>"]((__dict_Applicative_162["__superclass_Prelude.Apply_0"]())["__superclass_Prelude.Functor_0"]())(Prelude[":"])(f(_242[0])))(traverse(traversableArray)(__dict_Applicative_162)(f)(_305));
                };
                throw new Error("Failed pattern match");
            };
        };
    });
    return {
        Traversable: Traversable, 
        sequence: sequence, 
        traverse: traverse, 
        traversableArray: traversableArray
    };
})();
var PS = PS || {};
PS.Main = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Data_Foldable = PS.Data_Foldable;
    var Signal = PS.Signal;
    var Data_Traversable = PS.Data_Traversable;
    var Signal_DOM = PS.Signal_DOM;
    var Mario = PS.Mario;
    var Control_Monad_Eff = PS.Control_Monad_Eff;
    var DOM = PS.DOM;
    var Data_Array = PS.Data_Array;
    
  function updatePosition(node) {
    return function(coord) {
      return function() {
        node.style.left = coord.x + "px";
        node.style.bottom = coord.y + "px";
      };
    };
  }
  ;
    
  function updateSprite(node) {
    var a = document.createElement("a");
    return function(url) {
      return function() {
        a.href = url;
        if (node.src !== a.href) node.src = url;
      };
    };
  }
  ;
    
  function onDOMContentLoaded(action) {
    if (document.readyState === "interactive") {
      action();
    } else {
      document.addEventListener("DOMContentLoaded", action);
    }
    return function() { return {}; };
  }
  ;
    
  function getMario() { return document.getElementById("mario"); }
  ;
    var rightKeyCodes = [ 39, 68 ];
    var offsetGround = function (amount) {
        return function (pos) {
            var _306 = {};
            for (var _307 in pos) {
                if (pos.hasOwnProperty(_307)) {
                    _306[_307] = pos[_307];
                };
            };
            _306.y = (pos.y + amount) - 4;
            return _306;
        };
    };
    var mkInputs = function (l) {
        return function (r) {
            return function (j) {
                return {
                    left: l, 
                    right: r, 
                    jump: j
                };
            };
        };
    };
    var leftKeyCodes = [ 37, 65 ];
    var jumpKeyCodes = [ 38, 87 ];
    var groundHeight = 40;
    var combineKeyPresses = Data_Foldable.foldl(Data_Foldable.foldableArray)(Signal.merge)(Signal.constant(false));
    var main = onDOMContentLoaded(function __do() {
        var _12 = getMario();
        var _11 = Prelude["<$>"](Control_Monad_Eff.functorEff)(combineKeyPresses)(Data_Traversable.sequence(Data_Traversable.traversableArray)(Control_Monad_Eff.applicativeEff)(Prelude["<$>"](Data_Array.functorArray)(Signal_DOM.keyPressed)(leftKeyCodes)))();
        var _10 = Prelude["<$>"](Control_Monad_Eff.functorEff)(combineKeyPresses)(Data_Traversable.sequence(Data_Traversable.traversableArray)(Control_Monad_Eff.applicativeEff)(Prelude["<$>"](Data_Array.functorArray)(Signal_DOM.keyPressed)(rightKeyCodes)))();
        var _9 = Prelude["<$>"](Control_Monad_Eff.functorEff)(combineKeyPresses)(Data_Traversable.sequence(Data_Traversable.traversableArray)(Control_Monad_Eff.applicativeEff)(Prelude["<$>"](Data_Array.functorArray)(Signal_DOM.keyPressed)(jumpKeyCodes)))();
        return (function () {
            var inputs = Prelude["<*>"](Signal.applySignal)(Prelude["<*>"](Signal.applySignal)(Prelude["<$>"](Signal.functorSignal)(mkInputs)(_11))(_10))(_9);
            return function __do() {
                var _8 = Signal_DOM.animationFrame();
                return Signal.runSignal(Signal["~>"](Signal.functorSignal)(Signal.foldp(Mario.marioLogic)(Mario.initialState)(Signal.sampleOn(_8)(inputs)))(function (gameState) {
                    return function __do() {
                        updateSprite(_12)(Mario.marioSpriteUrl(Mario.currentActivity(gameState))(gameState.dir))();
                        return updatePosition(_12)(offsetGround(groundHeight)({
                            x: gameState.x, 
                            y: gameState.y
                        }))();
                    };
                }))();
            };
        })()();
    });
    return {
        main: main, 
        getMario: getMario, 
        onDOMContentLoaded: onDOMContentLoaded, 
        mkInputs: mkInputs, 
        combineKeyPresses: combineKeyPresses, 
        jumpKeyCodes: jumpKeyCodes, 
        rightKeyCodes: rightKeyCodes, 
        leftKeyCodes: leftKeyCodes, 
        updateSprite: updateSprite, 
        updatePosition: updatePosition, 
        offsetGround: offsetGround, 
        groundHeight: groundHeight
    };
})();

